DROP DATABASE IF EXISTS hsj;
DROP DATABASE ssafit;
CREATE DATABASE ssafit;

USE ssafit;

CREATE TABLE users (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    point INT DEFAULT 0
);

INSERT INTO users (user_id, point) VALUES ('이미림', 100);

#SET SQL_SAFE_UPDATES = 0;
#DELETE FROM users;
#SET SQL_SAFE_UPDATES = 1;

SELECT * FROM users;

#SET SQL_SAFE_UPDATES = 0;
#UPDATE users SET point = 0 WHERE id = 1;
#SET SQL_SAFE_UPDATES = 1;

